# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
title: Gonzalo Rivero
name: Gonzalo Rivero
email: me@griverorz.net
description: > # this means to ignore newlines until "url:"
  Homepage for Gonzalo Rivero.
footer_text: >
  Powered by <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.

url:  # the base hostname & protocol for your site
baseurl: 
last_updated: 

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------

navbar_fixed: true
footer_fixed: true

# Dimensions
max_width: 800px

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username: griverorz # your GitHub user name
twitter_username: griverorz # your Twitter handle
linkedin_username: # your LinkedIn user name
scholar_userid: DrJpGZEAAAAJ
orcid_id: # your ORCID ID
medium_username: # your Medium username
quora_username: # your Quora username
publons_id: # your ID on Publons
research_gate_profile: # your profile on ResearchGate
blogger_url: # your blogger URL
keybase_username: # your keybase user name

contact_note: >
  The best method to reach me is via email.

google_analytics: UA-48809017-2 # out your google-analytics code

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
blog_name: 
blog_description: a simple whitespace theme for academics
permalink: /blog/:year/:title/

# Pagination
pagination:
  enabled: true

# Comments
disqus_shortname: griverorz # put your disqus shortname

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/

news_limit: 5

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Markdown and syntax highlight
markdown: kramdown
highlighter: rouge

# Includes & excludes
include: ['_pages']
exclude: [vendor]

# Plug-ins
plugins:
  - jekyll-email-protect
  - jekyll-github-metadata
  - jekyll-paginate-v2
  - jekyll/scholar
  - jekyll-twitter-plugin
  - jemoji
  # - bootstrap
  # - material-sass

# -----------------------------------------------------------------------------
# Jekyll Scholar
# -----------------------------------------------------------------------------

scholar:

  last_name: Gonzalo Rivero

  style: apa
  locale: en

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

# -----------------------------------------------------------------------------
# Optional Features
# -----------------------------------------------------------------------------

enable_google_analytics:  false
enable_mansory:           true
enable_math:              true
enable_tooltips:          false
enable_darkmode:          true
show_social_icons:        false

# -----------------------------------------------------------------------------
# Library versions
# -----------------------------------------------------------------------------

academicons:
  version: "1.8.6"
  integrity: "sha256-uFVgMKfistnJAfoCUQigIl+JfUaP47GrRKjf6CTPVmw="
bootstrap:
  version: "4.4.1"
  integrity:
    css: "sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
    js: "sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
fontawesome:
  version: "5.13.0"
  integrity: "sha256-h20CPZ0QyXlBuAw7A+KluUYx/3pK+c7lYEpqLTlxjYQ="
jquery:
  version: "3.5.1"
  integrity: "sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg=="
mathjax:
  version: "3.1.2"
mansory:
  version: "4.2.2"
  integrity: "sha256-Nn1q/fx0H7SNLZMQ5Hw5JLaTRZp0yILA/FRexe19VdI="
mdb:
  version: "4.17.0"
  integrity:
    css: "sha256-/SwJ2GDcEt5382i8zqDwl36VJGECxEoIcBIuoLmLR4g="
    js: "sha256-UGNYR+uy841zU5TiO2yXD96UktHt9TM4/WXvsDLr4l0="
popper:
  version: "2.4.0"
  integrity: "sha256-OH05DFHUWzr725HmuHo3pnuvUUn+TJuj8/Qz9xytFEw="
